#= require jquery_ujs
#= require bootstrap
#= require handlebars
#= require ember
#= require ember-data
#= require_self
#= require restadapter
#= require spikes
@Spikes = Ember.Application.create()
#= require_tree .
